from sqlalchemy.orm import Session
from models.activity import Activity
from models.city import City

ACTIVITIES = [
    (1, "Eiffel Tower Visit", "SIGHTSEEING", 25, 3, "Iconic iron lattice tower"),
    (1, "Louvre Museum", "CULTURE", 17, 4, "World's largest art museum"),
    (1, "Seine River Cruise", "SIGHTSEEING", 15, 1.5, "Scenic boat ride"),
    (1, "Croissant Tasting Tour", "FOOD", 40, 3, "Best bakeries in Paris"),
    (1, "Montmartre Walk", "SIGHTSEEING", 0, 2, "Artistic hilltop neighborhood"),
    (1, "Palace of Versailles", "CULTURE", 20, 5, "Royal palace day trip"),
    (2, "Senso-ji Temple", "CULTURE", 0, 2, "Ancient Buddhist temple in Asakusa"),
    (2, "Tsukiji Outer Market", "FOOD", 30, 3, "Fresh sushi and street food"),
    (2, "Shibuya Crossing Experience", "SIGHTSEEING", 0, 1, "World's busiest pedestrian crossing"),
    (2, "Robot Restaurant Show", "NIGHTLIFE", 80, 2, "Wild robot cabaret show"),
    (2, "Mount Fuji Day Trip", "NATURE", 50, 8, "Iconic volcanic mountain"),
    (2, "Akihabara Electronics Tour", "SHOPPING", 0, 3, "Tech and anime district"),
    (3, "Statue of Liberty", "SIGHTSEEING", 24, 4, "Iconic symbol of freedom"),
    (3, "Central Park Bike Tour", "NATURE", 15, 3, "Cycling through Manhattan's park"),
    (3, "Broadway Show", "CULTURE", 120, 3, "World-class theater"),
    (3, "Brooklyn Bridge Walk", "SIGHTSEEING", 0, 1.5, "Iconic bridge walk with skyline views"),
    (3, "Top of the Rock", "SIGHTSEEING", 40, 1.5, "Panoramic NYC views"),
    (3, "Pizza Tour Little Italy", "FOOD", 45, 3, "Best NYC pizza spots"),
    (4, "Tower of London", "CULTURE", 30, 3, "Historic castle and fortress"),
    (4, "British Museum", "CULTURE", 0, 4, "World-class free museum"),
    (4, "London Eye", "SIGHTSEEING", 35, 1, "Giant Ferris wheel on the Thames"),
    (4, "Camden Market Food Tour", "FOOD", 25, 3, "Eclectic street food market"),
    (4, "Harry Potter Studio Tour", "CULTURE", 55, 4, "Behind-the-scenes movie magic"),
    (5, "Burj Khalifa Observation", "SIGHTSEEING", 40, 2, "World's tallest building"),
    (5, "Desert Safari", "ADVENTURE", 60, 6, "Dune bashing and camel rides"),
    (5, "Dubai Mall & Fountain Show", "SHOPPING", 0, 3, "World's largest mall"),
    (5, "Dhow Cruise Dinner", "FOOD", 55, 3, "Traditional boat dinner cruise"),
    (6, "Ubud Rice Terraces", "NATURE", 5, 3, "Stunning green terraces"),
    (6, "Temple Tour", "CULTURE", 10, 4, "Ancient Hindu temples"),
    (6, "Surfing in Kuta", "ADVENTURE", 25, 3, "Beginner-friendly waves"),
    (6, "Balinese Cooking Class", "FOOD", 35, 4, "Traditional cuisine workshop"),
    (6, "Sunrise Mt Batur Trek", "ADVENTURE", 45, 6, "Volcanic sunrise hike"),
    (7, "Colosseum Tour", "CULTURE", 18, 3, "Ancient Roman amphitheater"),
    (7, "Vatican Museums", "CULTURE", 20, 4, "Sistine Chapel and St Peter's"),
    (7, "Roman Food Tour", "FOOD", 50, 3.5, "Pasta, gelato, espresso"),
    (7, "Trevi Fountain Visit", "SIGHTSEEING", 0, 0.5, "Iconic Baroque fountain"),
    (8, "Sagrada Familia", "CULTURE", 26, 2, "Gaudi's unfinished masterpiece"),
    (8, "Park Güell", "SIGHTSEEING", 10, 2, "Colorful mosaic park"),
    (8, "La Boqueria Market", "FOOD", 20, 2, "Vibrant food market on La Rambla"),
    (8, "Flamenco Show", "CULTURE", 40, 2, "Traditional Spanish dance"),
    (9, "Sydney Opera House Tour", "CULTURE", 40, 1.5, "Architectural icon"),
    (9, "Bondi to Coogee Walk", "NATURE", 0, 3, "Stunning coastal trail"),
    (9, "Harbour Bridge Climb", "ADVENTURE", 180, 3.5, "Climb the iconic bridge"),
    (10, "Grand Palace & Wat Phra Kaew", "CULTURE", 15, 3, "Royal palace complex"),
    (10, "Street Food Tour", "FOOD", 20, 3, "Pad Thai, mango sticky rice"),
    (10, "Floating Market Trip", "SIGHTSEEING", 25, 4, "Traditional canal market"),
    (10, "Thai Boxing Show", "CULTURE", 30, 2, "Muay Thai live event"),
    (11, "Hagia Sophia", "CULTURE", 15, 2, "Byzantine cathedral turned mosque"),
    (11, "Grand Bazaar Shopping", "SHOPPING", 0, 3, "Historic covered market"),
    (11, "Bosphorus Cruise", "SIGHTSEEING", 20, 2, "Cruise between continents"),
    (11, "Turkish Bath Experience", "WELLNESS", 40, 2, "Traditional hamam spa"),
    (12, "Table Mountain Hike", "ADVENTURE", 15, 4, "Iconic flat-topped mountain"),
    (12, "Cape Point Drive", "NATURE", 20, 6, "Scenic coastal drive"),
    (12, "Wine Tasting Stellenbosch", "FOOD", 30, 5, "South African wine country"),
    (12, "Penguin Colony Visit", "NATURE", 10, 2, "African penguins at Boulders Beach"),
    (14, "Sunset in Oia", "SIGHTSEEING", 0, 2, "World-famous caldera sunset"),
    (14, "Wine Tasting Tour", "FOOD", 35, 3, "Volcanic wine varieties"),
    (14, "Red Beach Visit", "NATURE", 0, 2, "Unique red volcanic beach"),
    (15, "Fushimi Inari Shrine", "CULTURE", 0, 3, "Thousands of vermillion torii gates"),
    (15, "Arashiyama Bamboo Grove", "NATURE", 0, 2, "Ethereal bamboo forest walk"),
    (15, "Traditional Tea Ceremony", "CULTURE", 30, 1.5, "Authentic matcha experience"),
    (15, "Geisha District Walk", "CULTURE", 0, 2, "Gion evening stroll"),
    (18, "Anne Frank House", "CULTURE", 16, 1.5, "WWII historic house museum"),
    (18, "Canal Cruise", "SIGHTSEEING", 15, 1, "Scenic waterway tour"),
    (18, "Van Gogh Museum", "CULTURE", 20, 2.5, "World's largest Van Gogh collection"),
    (18, "Heineken Experience", "FOOD", 21, 2, "Beer brewery tour"),
    (19, "Gardens by the Bay", "NATURE", 20, 3, "Futuristic garden park"),
    (19, "Hawker Center Food Tour", "FOOD", 15, 2.5, "Michelin-star street food"),
    (19, "Marina Bay Sands SkyPark", "SIGHTSEEING", 26, 1.5, "Infinity pool skyline views"),
    (19, "Sentosa Island", "ADVENTURE", 30, 5, "Beach resort island"),
    (20, "Christ the Redeemer", "SIGHTSEEING", 15, 3, "Iconic hilltop statue"),
    (20, "Copacabana Beach", "NATURE", 0, 3, "Famous crescent beach"),
    (20, "Sugarloaf Mountain Cable Car", "SIGHTSEEING", 25, 2, "Panoramic views"),
    (20, "Samba Dance Class", "CULTURE", 20, 2, "Learn Brazilian dance"),
]


def seed_activities(db: Session):
    if db.query(Activity).count() > 0:
        return
    for city_id, name, atype, cost, duration, desc in ACTIVITIES:
        city = db.query(City).filter(City.id == city_id).first()
        if city:
            db.add(Activity(city_id=city_id, name=name, type=atype,
                           estimated_cost=cost, duration_hours=duration, description=desc))
    db.commit()
