from sqlalchemy.orm import Session
from models.city import City
from seed.city_photos import CITY_PHOTOS

# Latitude/longitude for every seeded city (used by the map views).
CITY_COORDS = {
    "Paris": (48.8566, 2.3522),
    "Tokyo": (35.6762, 139.6503),
    "New York": (40.7128, -74.006),
    "London": (51.5074, -0.1278),
    "Dubai": (25.2048, 55.2708),
    "Bali": (-8.3405, 115.092),
    "Rome": (41.9028, 12.4964),
    "Barcelona": (41.3874, 2.1686),
    "Sydney": (-33.8688, 151.2093),
    "Bangkok": (13.7563, 100.5018),
    "Istanbul": (41.0082, 28.9784),
    "Cape Town": (-33.9249, 18.4241),
    "Marrakech": (31.6295, -7.9811),
    "Santorini": (36.461, 25.376),
    "Kyoto": (35.0116, 135.7681),
    "Cusco": (-13.532, -71.9675),
    "Reykjavik": (64.1466, -21.9426),
    "Amsterdam": (52.3676, 4.9041),
    "Singapore": (1.3521, 103.8198),
    "Rio de Janeiro": (-22.9068, -43.1729),
    "Prague": (50.0755, 14.4378),
    "Lisbon": (38.7223, -9.1393),
    "Seoul": (37.5665, 126.978),
    "Vienna": (48.2082, 16.3738),
    "Buenos Aires": (-34.6037, -58.3816),
    "Maldives": (4.1755, 73.5093),
    "Jaipur": (26.9124, 75.7873),
    "Havana": (23.1136, -82.3666),
    "Cairo": (30.0444, 31.2357),
    "Vancouver": (49.2827, -123.1207),
    "Dubrovnik": (42.6507, 18.0944),
    "Petra": (30.3285, 35.4444),
    "Queenstown": (-45.0312, 168.6626),
    "Hanoi": (21.0278, 105.8342),
    "Florence": (43.7696, 11.2558),
    "Amalfi Coast": (40.6281, 14.485),
    "Chiang Mai": (18.7883, 98.9853),
    "Zürich": (47.3769, 8.5417),
    "Maui": (20.7984, -156.3319),
    "Colombo": (6.9271, 79.8612),
    "Kathmandu": (27.7172, 85.324),
    "Edinburgh": (55.9533, -3.1883),
    "Munich": (48.1351, 11.582),
    "San Francisco": (37.7749, -122.4194),
    "Phuket": (7.8804, 98.3923),
    "Cartagena": (10.391, -75.4794),
    "Lhasa": (29.652, 91.1721),
    "Nairobi": (-1.2921, 36.8219),
    "Athens": (37.9838, 23.7275),
    "Mexico City": (19.4326, -99.1332),
    "Berlin": (52.52, 13.405),
    "Copenhagen": (55.6761, 12.5683),
    "Helsinki": (60.1699, 24.9384),
    "Oslo": (59.9139, 10.7522),
    "Stockholm": (59.3293, 18.0686),
    "Bruges": (51.2093, 3.2247),
    "Budapest": (47.4979, 19.0402),
    "Krakow": (50.0647, 19.945),
    "Nice": (43.7102, 7.262),
    "Porto": (41.1579, -8.6291),
    "Seville": (37.3891, -5.9845),
    "Split": (43.5081, 16.4402),
    "Moscow": (55.7558, 37.6173),
    "Tallinn": (59.437, 24.7536),
    "Tbilisi": (41.7151, 44.8271),
    "Kuala Lumpur": (3.139, 101.6869),
    "Mumbai": (19.076, 72.8777),
    "Delhi": (28.7041, 77.1025),
    "Goa": (15.2993, 74.124),
    "Hong Kong": (22.3193, 114.1694),
    "Shanghai": (31.2304, 121.4737),
    "Beijing": (39.9042, 116.4074),
    "Taipei": (25.033, 121.5654),
    "Osaka": (34.6937, 135.5023),
    "Siem Reap": (13.3671, 103.8448),
    "Luang Prabang": (19.8856, 102.1347),
    "Zanzibar": (-6.1659, 39.199),
    "Victoria Falls": (-17.9243, 25.8572),
    "Casablanca": (33.5731, -7.5898),
    "Accra": (5.6037, -0.187),
    "Lima": (-12.0464, -77.0428),
    "Bogota": (4.711, -74.0721),
    "Santiago": (-33.4489, -70.6693),
    "Quito": (-0.1807, -78.4678),
    "Medellín": (6.2442, -75.5812),
    "Muscat": (23.588, 58.3829),
    "Toronto": (43.6532, -79.3832),
    "Montreal": (45.5017, -73.5673),
    "Los Angeles": (34.0522, -118.2437),
    "Miami": (25.7617, -80.1918),
    "Chicago": (41.8781, -87.6298),
    "Cancún": (21.1619, -86.8515),
    "Doha": (25.2854, 51.531),
    "Abu Dhabi": (24.4539, 54.3773),
    "Tel Aviv": (32.0853, 34.7818),
    "Amman": (31.9454, 35.9284),
    "Melbourne": (-37.8136, 144.9631),
    "Auckland": (-36.8485, 174.7633),
    "Fiji": (-17.7134, 178.065),
    "Valletta": (35.8989, 14.5146),
    "Salzburg": (47.8095, 13.055),
    "Lucerne": (47.0502, 8.3093),
    "Varanasi": (25.3176, 82.9739),
    "Ho Chi Minh City": (10.8231, 106.6297),
    "Udaipur": (24.5854, 73.7125),
}

CITIES_DATA = [
    {"name": "Paris", "country": "France", "region": "Europe", "cost_index": 1.8, "popularity_score": 98, "description": "City of Light, romance, Eiffel Tower, world-class cuisine", "image_url": CITY_PHOTOS['Paris']["image_url"]},
    {"name": "Tokyo", "country": "Japan", "region": "Asia", "cost_index": 1.6, "popularity_score": 96, "description": "Blend of ultramodern and traditional, cherry blossoms, sushi", "image_url": CITY_PHOTOS['Tokyo']["image_url"]},
    {"name": "New York", "country": "USA", "region": "North America", "cost_index": 2.0, "popularity_score": 97, "description": "The Big Apple, Times Square, Central Park, Broadway", "image_url": CITY_PHOTOS['New York']["image_url"]},
    {"name": "London", "country": "UK", "region": "Europe", "cost_index": 1.9, "popularity_score": 95, "description": "Big Ben, Buckingham Palace, British Museum", "image_url": CITY_PHOTOS['London']["image_url"]},
    {"name": "Dubai", "country": "UAE", "region": "Middle East", "cost_index": 1.7, "popularity_score": 93, "description": "Futuristic skyline, luxury shopping, desert adventures", "image_url": CITY_PHOTOS['Dubai']["image_url"]},
    {"name": "Bali", "country": "Indonesia", "region": "Asia", "cost_index": 0.6, "popularity_score": 92, "description": "Tropical paradise, temples, rice terraces, surf", "image_url": CITY_PHOTOS['Bali']["image_url"]},
    {"name": "Rome", "country": "Italy", "region": "Europe", "cost_index": 1.4, "popularity_score": 94, "description": "Colosseum, Vatican, pasta, ancient history", "image_url": CITY_PHOTOS['Rome']["image_url"]},
    {"name": "Barcelona", "country": "Spain", "region": "Europe", "cost_index": 1.3, "popularity_score": 91, "description": "Gaudi architecture, beaches, tapas, vibrant nightlife", "image_url": CITY_PHOTOS['Barcelona']["image_url"]},
    {"name": "Sydney", "country": "Australia", "region": "Oceania", "cost_index": 1.7, "popularity_score": 89, "description": "Opera House, Harbour Bridge, Bondi Beach", "image_url": CITY_PHOTOS['Sydney']["image_url"]},
    {"name": "Bangkok", "country": "Thailand", "region": "Asia", "cost_index": 0.5, "popularity_score": 90, "description": "Street food, temples, floating markets, nightlife", "image_url": CITY_PHOTOS['Bangkok']["image_url"]},
    {"name": "Istanbul", "country": "Turkey", "region": "Europe", "cost_index": 0.7, "popularity_score": 88, "description": "Where East meets West, Grand Bazaar, Blue Mosque", "image_url": CITY_PHOTOS['Istanbul']["image_url"]},
    {"name": "Cape Town", "country": "South Africa", "region": "Africa", "cost_index": 0.8, "popularity_score": 85, "description": "Table Mountain, vineyards, penguins, Cape of Good Hope", "image_url": CITY_PHOTOS['Cape Town']["image_url"]},
    {"name": "Marrakech", "country": "Morocco", "region": "Africa", "cost_index": 0.5, "popularity_score": 84, "description": "Souks, riads, Sahara gateway, spice markets", "image_url": CITY_PHOTOS['Marrakech']["image_url"]},
    {"name": "Santorini", "country": "Greece", "region": "Europe", "cost_index": 1.5, "popularity_score": 90, "description": "White-washed buildings, blue domes, stunning sunsets", "image_url": CITY_PHOTOS['Santorini']["image_url"]},
    {"name": "Kyoto", "country": "Japan", "region": "Asia", "cost_index": 1.4, "popularity_score": 88, "description": "Ancient temples, geisha district, bamboo forests", "image_url": CITY_PHOTOS['Kyoto']["image_url"]},
    {"name": "Cusco", "country": "Peru", "region": "South America", "cost_index": 0.5, "popularity_score": 83, "description": "Gateway to Machu Picchu, Inca heritage", "image_url": CITY_PHOTOS['Cusco']["image_url"]},
    {"name": "Reykjavik", "country": "Iceland", "region": "Europe", "cost_index": 2.1, "popularity_score": 82, "description": "Northern lights, geysers, Blue Lagoon", "image_url": CITY_PHOTOS['Reykjavik']["image_url"]},
    {"name": "Amsterdam", "country": "Netherlands", "region": "Europe", "cost_index": 1.5, "popularity_score": 89, "description": "Canals, Van Gogh Museum, tulips, cycling culture", "image_url": CITY_PHOTOS['Amsterdam']["image_url"]},
    {"name": "Singapore", "country": "Singapore", "region": "Asia", "cost_index": 1.8, "popularity_score": 87, "description": "Gardens by the Bay, Marina Bay Sands, hawker centers", "image_url": CITY_PHOTOS['Singapore']["image_url"]},
    {"name": "Rio de Janeiro", "country": "Brazil", "region": "South America", "cost_index": 0.9, "popularity_score": 86, "description": "Christ the Redeemer, Copacabana, Carnival", "image_url": CITY_PHOTOS['Rio de Janeiro']["image_url"]},
    {"name": "Prague", "country": "Czech Republic", "region": "Europe", "cost_index": 0.9, "popularity_score": 86, "description": "Gothic architecture, Charles Bridge, affordable beer", "image_url": CITY_PHOTOS['Prague']["image_url"]},
    {"name": "Lisbon", "country": "Portugal", "region": "Europe", "cost_index": 1.0, "popularity_score": 85, "description": "Tram 28, pastéis de nata, fado music, colorful tiles", "image_url": CITY_PHOTOS['Lisbon']["image_url"]},
    {"name": "Seoul", "country": "South Korea", "region": "Asia", "cost_index": 1.2, "popularity_score": 84, "description": "K-pop culture, street food, palaces, tech hub", "image_url": CITY_PHOTOS['Seoul']["image_url"]},
    {"name": "Vienna", "country": "Austria", "region": "Europe", "cost_index": 1.4, "popularity_score": 83, "description": "Classical music, coffee houses, imperial palaces", "image_url": CITY_PHOTOS['Vienna']["image_url"]},
    {"name": "Buenos Aires", "country": "Argentina", "region": "South America", "cost_index": 0.6, "popularity_score": 82, "description": "Tango, steakhouses, colorful La Boca district", "image_url": CITY_PHOTOS['Buenos Aires']["image_url"]},
    {"name": "Maldives", "country": "Maldives", "region": "Asia", "cost_index": 2.5, "popularity_score": 91, "description": "Overwater villas, crystal clear waters, coral reefs", "image_url": CITY_PHOTOS['Maldives']["image_url"]},
    {"name": "Jaipur", "country": "India", "region": "Asia", "cost_index": 0.3, "popularity_score": 80, "description": "Pink City, Hawa Mahal, Amber Fort, colorful bazaars", "image_url": CITY_PHOTOS['Jaipur']["image_url"]},
    {"name": "Havana", "country": "Cuba", "region": "Caribbean", "cost_index": 0.6, "popularity_score": 79, "description": "Vintage cars, salsa music, colonial architecture", "image_url": CITY_PHOTOS['Havana']["image_url"]},
    {"name": "Cairo", "country": "Egypt", "region": "Africa", "cost_index": 0.4, "popularity_score": 81, "description": "Pyramids of Giza, Sphinx, Nile River cruises", "image_url": CITY_PHOTOS['Cairo']["image_url"]},
    {"name": "Vancouver", "country": "Canada", "region": "North America", "cost_index": 1.6, "popularity_score": 83, "description": "Mountains meets ocean, Stanley Park, diverse cuisine", "image_url": CITY_PHOTOS['Vancouver']["image_url"]},
    {"name": "Dubrovnik", "country": "Croatia", "region": "Europe", "cost_index": 1.2, "popularity_score": 84, "description": "King's Landing, city walls, Adriatic coast", "image_url": CITY_PHOTOS['Dubrovnik']["image_url"]},
    {"name": "Petra", "country": "Jordan", "region": "Middle East", "cost_index": 0.8, "popularity_score": 80, "description": "Rose-red city, ancient Nabataean ruins, desert treks", "image_url": CITY_PHOTOS['Petra']["image_url"]},
    {"name": "Queenstown", "country": "New Zealand", "region": "Oceania", "cost_index": 1.6, "popularity_score": 82, "description": "Adventure capital, bungee jumping, fjords, LOTR scenery", "image_url": CITY_PHOTOS['Queenstown']["image_url"]},
    {"name": "Hanoi", "country": "Vietnam", "region": "Asia", "cost_index": 0.3, "popularity_score": 81, "description": "Old Quarter, pho, Ha Long Bay gateway, French colonial charm", "image_url": CITY_PHOTOS['Hanoi']["image_url"]},
    {"name": "Florence", "country": "Italy", "region": "Europe", "cost_index": 1.4, "popularity_score": 87, "description": "Renaissance art, Duomo, Uffizi Gallery, Tuscan cuisine", "image_url": CITY_PHOTOS['Florence']["image_url"]},
    {"name": "Amalfi Coast", "country": "Italy", "region": "Europe", "cost_index": 1.8, "popularity_score": 86, "description": "Cliffside villages, Mediterranean views, limoncello", "image_url": CITY_PHOTOS['Amalfi Coast']["image_url"]},
    {"name": "Chiang Mai", "country": "Thailand", "region": "Asia", "cost_index": 0.3, "popularity_score": 80, "description": "Temple hopping, night bazaars, elephant sanctuaries", "image_url": CITY_PHOTOS['Chiang Mai']["image_url"]},
    {"name": "Zürich", "country": "Switzerland", "region": "Europe", "cost_index": 2.3, "popularity_score": 79, "description": "Alpine scenery, chocolate, banking capital, pristine lakes", "image_url": CITY_PHOTOS['Zürich']["image_url"]},
    {"name": "Maui", "country": "USA", "region": "North America", "cost_index": 2.0, "popularity_score": 85, "description": "Tropical beaches, Road to Hana, whale watching", "image_url": CITY_PHOTOS['Maui']["image_url"]},
    {"name": "Colombo", "country": "Sri Lanka", "region": "Asia", "cost_index": 0.4, "popularity_score": 75, "description": "Temples, colonial history, gateway to Sri Lanka", "image_url": CITY_PHOTOS['Colombo']["image_url"]},
    {"name": "Kathmandu", "country": "Nepal", "region": "Asia", "cost_index": 0.3, "popularity_score": 76, "description": "Himalayan gateway, temples, trekking base", "image_url": CITY_PHOTOS['Kathmandu']["image_url"]},
    {"name": "Edinburgh", "country": "UK", "region": "Europe", "cost_index": 1.5, "popularity_score": 82, "description": "Castle, Royal Mile, Arthur's Seat, whisky tours", "image_url": CITY_PHOTOS['Edinburgh']["image_url"]},
    {"name": "Munich", "country": "Germany", "region": "Europe", "cost_index": 1.4, "popularity_score": 81, "description": "Oktoberfest, beer gardens, BMW museum, Alpine gateway", "image_url": CITY_PHOTOS['Munich']["image_url"]},
    {"name": "San Francisco", "country": "USA", "region": "North America", "cost_index": 2.1, "popularity_score": 84, "description": "Golden Gate Bridge, cable cars, tech hub, Alcatraz", "image_url": CITY_PHOTOS['San Francisco']["image_url"]},
    {"name": "Phuket", "country": "Thailand", "region": "Asia", "cost_index": 0.5, "popularity_score": 83, "description": "Island paradise, beach resorts, Phi Phi Islands", "image_url": CITY_PHOTOS['Phuket']["image_url"]},
    {"name": "Cartagena", "country": "Colombia", "region": "South America", "cost_index": 0.5, "popularity_score": 78, "description": "Colorful colonial old town, Caribbean beaches", "image_url": CITY_PHOTOS['Cartagena']["image_url"]},
    {"name": "Lhasa", "country": "China", "region": "Asia", "cost_index": 0.7, "popularity_score": 74, "description": "Potala Palace, Tibetan Buddhism, rooftop of the world", "image_url": CITY_PHOTOS['Lhasa']["image_url"]},
    {"name": "Nairobi", "country": "Kenya", "region": "Africa", "cost_index": 0.6, "popularity_score": 77, "description": "Safari gateway, Nairobi National Park, wildlife", "image_url": CITY_PHOTOS['Nairobi']["image_url"]},
    {"name": "Athens", "country": "Greece", "region": "Europe", "cost_index": 1.0, "popularity_score": 83, "description": "Acropolis, Parthenon, cradle of Western civilization", "image_url": CITY_PHOTOS['Athens']["image_url"]},
    {"name": "Mexico City", "country": "Mexico", "region": "North America", "cost_index": 0.5, "popularity_score": 82, "description": "Aztec ruins, incredible food, Frida Kahlo, mezcal", "image_url": CITY_PHOTOS['Mexico City']["image_url"]},
    # ── Additional 55 cities to reach 100+ ──
    {"name": "Berlin", "country": "Germany", "region": "Europe", "cost_index": 1.2, "popularity_score": 86, "description": "Vibrant art scene, history, techno, street food", "image_url": CITY_PHOTOS['Berlin']["image_url"]},
    {"name": "Copenhagen", "country": "Denmark", "region": "Europe", "cost_index": 1.9, "popularity_score": 83, "description": "Hygge culture, Tivoli Gardens, Nyhavn canal", "image_url": CITY_PHOTOS['Copenhagen']["image_url"]},
    {"name": "Helsinki", "country": "Finland", "region": "Europe", "cost_index": 1.7, "popularity_score": 78, "description": "Design capital, saunas, northern lights, islands", "image_url": CITY_PHOTOS['Helsinki']["image_url"]},
    {"name": "Oslo", "country": "Norway", "region": "Europe", "cost_index": 2.2, "popularity_score": 79, "description": "Fjords, Viking history, Munch museum", "image_url": CITY_PHOTOS['Oslo']["image_url"]},
    {"name": "Stockholm", "country": "Sweden", "region": "Europe", "cost_index": 1.8, "popularity_score": 82, "description": "Archipelago, Gamla Stan, ABBA museum, Nobel Prize", "image_url": CITY_PHOTOS['Stockholm']["image_url"]},
    {"name": "Bruges", "country": "Belgium", "region": "Europe", "cost_index": 1.3, "popularity_score": 80, "description": "Medieval charm, chocolate, beer, canals", "image_url": CITY_PHOTOS['Bruges']["image_url"]},
    {"name": "Budapest", "country": "Hungary", "region": "Europe", "cost_index": 0.8, "popularity_score": 85, "description": "Thermal baths, ruin bars, Danube views, Parliament", "image_url": CITY_PHOTOS['Budapest']["image_url"]},
    {"name": "Krakow", "country": "Poland", "region": "Europe", "cost_index": 0.6, "popularity_score": 81, "description": "Old Town, Wawel Castle, salt mines, Jewish Quarter", "image_url": CITY_PHOTOS['Krakow']["image_url"]},
    {"name": "Nice", "country": "France", "region": "Europe", "cost_index": 1.5, "popularity_score": 82, "description": "French Riviera, Promenade des Anglais, beaches", "image_url": CITY_PHOTOS['Nice']["image_url"]},
    {"name": "Porto", "country": "Portugal", "region": "Europe", "cost_index": 0.9, "popularity_score": 83, "description": "Port wine, Douro Valley, azulejo tiles, Ribeira", "image_url": CITY_PHOTOS['Porto']["image_url"]},
    {"name": "Seville", "country": "Spain", "region": "Europe", "cost_index": 1.0, "popularity_score": 82, "description": "Flamenco, Alcázar, Plaza de España, tapas", "image_url": CITY_PHOTOS['Seville']["image_url"]},
    {"name": "Split", "country": "Croatia", "region": "Europe", "cost_index": 1.0, "popularity_score": 80, "description": "Diocletian's Palace, Adriatic beaches, island hopping", "image_url": CITY_PHOTOS['Split']["image_url"]},
    {"name": "Moscow", "country": "Russia", "region": "Europe", "cost_index": 1.1, "popularity_score": 80, "description": "Red Square, Kremlin, St Basil's Cathedral, ballet", "image_url": CITY_PHOTOS['Moscow']["image_url"]},
    {"name": "Tallinn", "country": "Estonia", "region": "Europe", "cost_index": 0.9, "popularity_score": 77, "description": "Medieval old town, digital nomad hub, Baltic charm", "image_url": CITY_PHOTOS['Tallinn']["image_url"]},
    {"name": "Tbilisi", "country": "Georgia", "region": "Europe", "cost_index": 0.4, "popularity_score": 76, "description": "Wine country, sulfur baths, Narikala fortress", "image_url": CITY_PHOTOS['Tbilisi']["image_url"]},
    {"name": "Kuala Lumpur", "country": "Malaysia", "region": "Asia", "cost_index": 0.5, "popularity_score": 82, "description": "Petronas Towers, street food, Batu Caves", "image_url": CITY_PHOTOS['Kuala Lumpur']["image_url"]},
    {"name": "Mumbai", "country": "India", "region": "Asia", "cost_index": 0.4, "popularity_score": 81, "description": "Gateway of India, Bollywood, street food capital", "image_url": CITY_PHOTOS['Mumbai']["image_url"]},
    {"name": "Delhi", "country": "India", "region": "Asia", "cost_index": 0.3, "popularity_score": 80, "description": "Red Fort, Qutub Minar, Chandni Chowk, history", "image_url": CITY_PHOTOS['Delhi']["image_url"]},
    {"name": "Goa", "country": "India", "region": "Asia", "cost_index": 0.3, "popularity_score": 79, "description": "Beaches, Portuguese heritage, nightlife, seafood", "image_url": CITY_PHOTOS['Goa']["image_url"]},
    {"name": "Hong Kong", "country": "China", "region": "Asia", "cost_index": 1.6, "popularity_score": 87, "description": "Skyline, dim sum, Victoria Peak, shopping paradise", "image_url": CITY_PHOTOS['Hong Kong']["image_url"]},
    {"name": "Shanghai", "country": "China", "region": "Asia", "cost_index": 1.2, "popularity_score": 84, "description": "The Bund, futuristic Pudong, dumpling heaven", "image_url": CITY_PHOTOS['Shanghai']["image_url"]},
    {"name": "Beijing", "country": "China", "region": "Asia", "cost_index": 1.1, "popularity_score": 85, "description": "Great Wall, Forbidden City, Peking duck, hutongs", "image_url": CITY_PHOTOS['Beijing']["image_url"]},
    {"name": "Taipei", "country": "Taiwan", "region": "Asia", "cost_index": 0.8, "popularity_score": 81, "description": "Night markets, Taipei 101, hot springs, bubble tea", "image_url": CITY_PHOTOS['Taipei']["image_url"]},
    {"name": "Osaka", "country": "Japan", "region": "Asia", "cost_index": 1.3, "popularity_score": 85, "description": "Street food capital, Osaka Castle, Dotonbori", "image_url": CITY_PHOTOS['Osaka']["image_url"]},
    {"name": "Siem Reap", "country": "Cambodia", "region": "Asia", "cost_index": 0.3, "popularity_score": 80, "description": "Angkor Wat, ancient temples, floating villages", "image_url": CITY_PHOTOS['Siem Reap']["image_url"]},
    {"name": "Luang Prabang", "country": "Laos", "region": "Asia", "cost_index": 0.3, "popularity_score": 76, "description": "Buddhist monks, Mekong River, waterfalls, French colonial", "image_url": CITY_PHOTOS['Luang Prabang']["image_url"]},
    {"name": "Zanzibar", "country": "Tanzania", "region": "Africa", "cost_index": 0.5, "popularity_score": 78, "description": "Spice island, Stone Town, turquoise waters", "image_url": CITY_PHOTOS['Zanzibar']["image_url"]},
    {"name": "Victoria Falls", "country": "Zimbabwe", "region": "Africa", "cost_index": 0.7, "popularity_score": 79, "description": "Smoke that thunders, bungee jumping, wildlife", "image_url": CITY_PHOTOS['Victoria Falls']["image_url"]},
    {"name": "Casablanca", "country": "Morocco", "region": "Africa", "cost_index": 0.5, "popularity_score": 76, "description": "Hassan II Mosque, Art Deco architecture, coastal city", "image_url": CITY_PHOTOS['Casablanca']["image_url"]},
    {"name": "Accra", "country": "Ghana", "region": "Africa", "cost_index": 0.5, "popularity_score": 74, "description": "Vibrant markets, beaches, slave forts, jollof rice", "image_url": CITY_PHOTOS['Accra']["image_url"]},
    {"name": "Lima", "country": "Peru", "region": "South America", "cost_index": 0.6, "popularity_score": 81, "description": "Ceviche capital, colonial center, Miraflores cliffs", "image_url": CITY_PHOTOS['Lima']["image_url"]},
    {"name": "Bogota", "country": "Colombia", "region": "South America", "cost_index": 0.5, "popularity_score": 78, "description": "La Candelaria, street art, coffee culture, Monserrate", "image_url": CITY_PHOTOS['Bogota']["image_url"]},
    {"name": "Santiago", "country": "Chile", "region": "South America", "cost_index": 0.8, "popularity_score": 79, "description": "Andes backdrop, wine valleys, vibrant food scene", "image_url": CITY_PHOTOS['Santiago']["image_url"]},
    {"name": "Quito", "country": "Ecuador", "region": "South America", "cost_index": 0.4, "popularity_score": 77, "description": "Colonial old town, Equator line, gateway to Galapagos", "image_url": CITY_PHOTOS['Quito']["image_url"]},
    {"name": "Medellín", "country": "Colombia", "region": "South America", "cost_index": 0.4, "popularity_score": 80, "description": "City of eternal spring, cable cars, innovation hub", "image_url": CITY_PHOTOS['Medellín']["image_url"]},
    {"name": "Muscat", "country": "Oman", "region": "Middle East", "cost_index": 1.1, "popularity_score": 75, "description": "Grand Mosque, souks, wadis, desert camping, pristine beaches", "image_url": CITY_PHOTOS['Muscat']["image_url"]},
    {"name": "Toronto", "country": "Canada", "region": "North America", "cost_index": 1.5, "popularity_score": 83, "description": "CN Tower, multicultural food, Niagara Falls nearby", "image_url": CITY_PHOTOS['Toronto']["image_url"]},
    {"name": "Montreal", "country": "Canada", "region": "North America", "cost_index": 1.3, "popularity_score": 81, "description": "French-Canadian culture, poutine, festivals, old port", "image_url": CITY_PHOTOS['Montreal']["image_url"]},
    {"name": "Los Angeles", "country": "USA", "region": "North America", "cost_index": 1.8, "popularity_score": 86, "description": "Hollywood, beaches, Santa Monica, diverse food scene", "image_url": CITY_PHOTOS['Los Angeles']["image_url"]},
    {"name": "Miami", "country": "USA", "region": "North America", "cost_index": 1.7, "popularity_score": 84, "description": "South Beach, Art Deco, Little Havana, nightlife", "image_url": CITY_PHOTOS['Miami']["image_url"]},
    {"name": "Chicago", "country": "USA", "region": "North America", "cost_index": 1.5, "popularity_score": 83, "description": "Deep-dish pizza, architecture, Navy Pier, blues music", "image_url": CITY_PHOTOS['Chicago']["image_url"]},
    {"name": "Cancún", "country": "Mexico", "region": "North America", "cost_index": 0.8, "popularity_score": 84, "description": "Caribbean beaches, Mayan ruins, cenotes, all-inclusive", "image_url": CITY_PHOTOS['Cancún']["image_url"]},
    {"name": "Doha", "country": "Qatar", "region": "Middle East", "cost_index": 1.6, "popularity_score": 77, "description": "Museum of Islamic Art, souq, desert safari, futuristic", "image_url": CITY_PHOTOS['Doha']["image_url"]},
    {"name": "Abu Dhabi", "country": "UAE", "region": "Middle East", "cost_index": 1.7, "popularity_score": 80, "description": "Sheikh Zayed Mosque, Louvre, Yas Island, luxury", "image_url": CITY_PHOTOS['Abu Dhabi']["image_url"]},
    {"name": "Tel Aviv", "country": "Israel", "region": "Middle East", "cost_index": 1.6, "popularity_score": 81, "description": "Beaches, Bauhaus, nightlife, startup hub, hummus", "image_url": CITY_PHOTOS['Tel Aviv']["image_url"]},
    {"name": "Amman", "country": "Jordan", "region": "Middle East", "cost_index": 0.7, "popularity_score": 76, "description": "Roman ruins, cuisine, Dead Sea gateway, hospitality", "image_url": CITY_PHOTOS['Amman']["image_url"]},
    {"name": "Melbourne", "country": "Australia", "region": "Oceania", "cost_index": 1.6, "popularity_score": 85, "description": "Coffee culture, street art, MCG, Great Ocean Road", "image_url": CITY_PHOTOS['Melbourne']["image_url"]},
    {"name": "Auckland", "country": "New Zealand", "region": "Oceania", "cost_index": 1.5, "popularity_score": 80, "description": "City of sails, Sky Tower, volcanic islands, diverse", "image_url": CITY_PHOTOS['Auckland']["image_url"]},
    {"name": "Fiji", "country": "Fiji", "region": "Oceania", "cost_index": 1.3, "popularity_score": 81, "description": "Crystal waters, coral reefs, Bula spirit, island life", "image_url": CITY_PHOTOS['Fiji']["image_url"]},
    {"name": "Valletta", "country": "Malta", "region": "Europe", "cost_index": 1.1, "popularity_score": 78, "description": "Knights of Malta, baroque architecture, blue waters", "image_url": CITY_PHOTOS['Valletta']["image_url"]},
    {"name": "Salzburg", "country": "Austria", "region": "Europe", "cost_index": 1.4, "popularity_score": 80, "description": "Sound of Music, Mozart, alpine scenery, fortress", "image_url": CITY_PHOTOS['Salzburg']["image_url"]},
    {"name": "Lucerne", "country": "Switzerland", "region": "Europe", "cost_index": 2.2, "popularity_score": 81, "description": "Chapel Bridge, Lake Lucerne, Mt Pilatus, charming old town", "image_url": CITY_PHOTOS['Lucerne']["image_url"]},
    {"name": "Varanasi", "country": "India", "region": "Asia", "cost_index": 0.2, "popularity_score": 78, "description": "Holy city, Ganges ghats, ancient temples, spiritual", "image_url": CITY_PHOTOS['Varanasi']["image_url"]},
    {"name": "Ho Chi Minh City", "country": "Vietnam", "region": "Asia", "cost_index": 0.3, "popularity_score": 82, "description": "War Remnants Museum, Cu Chi Tunnels, street food, buzz", "image_url": CITY_PHOTOS['Ho Chi Minh City']["image_url"]},
    {"name": "Udaipur", "country": "India", "region": "Asia", "cost_index": 0.3, "popularity_score": 78, "description": "City of Lakes, palatial architecture, romantic sunsets", "image_url": CITY_PHOTOS['Udaipur']["image_url"]},
]


def seed_cities(db: Session):
    """Seed new installs and replace only the old bundled photos on existing installs.

    Match by name + country, never by row position. Custom city photos are kept.
    Rows that predate map support also get their coordinates backfilled.
    """
    cities = {(city.name, city.country): city for city in db.query(City).all()}
    for data in CITIES_DATA:
        city = cities.get((data["name"], data["country"]))
        coords = CITY_COORDS.get(data["name"])
        if city is None:
            if coords:
                data = {**data, "latitude": coords[0], "longitude": coords[1]}
            db.add(City(**data))
        else:
            if coords and (city.latitude is None or city.longitude is None):
                city.latitude = coords[0]
                city.longitude = coords[1]
            photo = CITY_PHOTOS[data["name"]]
            if not city.image_url or city.image_url in photo["legacy_urls"]:
                city.image_url = photo["image_url"]
    db.commit()

